In [30]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [31]:
# Load the data and keep important columns
standard_informer = pd.read_csv('./dataset_results/informer_loss_functions_results_unscaled.csv')[['Pred_len', 'Loss_function', 'RMSE', 'MAE']]
standard_patchtst = pd.read_csv('./dataset_results/patchtst_loss_functions_results_unscaled.csv')[['Pred_len', 'Loss_function', 'RMSE', 'MAE']]

minmax_0_1_relu_informer = pd.read_csv('./dataset_results/informer_loss_functions_results_unscaled_minmax_0_1_relu.csv')[['Pred_len', 'Loss_function', 'RMSE', 'MAE']]
minmax_0_1_relu_patchtst = pd.read_csv('./dataset_results/patchtst_loss_functions_results_unscaled_minmax_0_1_relu.csv')[['Pred_len', 'Loss_function', 'RMSE', 'MAE']]

minmax_0_5_relu_informer = pd.read_csv('./dataset_results/informer_loss_functions_results_unscaled_minmax_0_5_relu.csv')[['Pred_len', 'Loss_function', 'RMSE', 'MAE']]
minmax_0_5_relu_patchtst = pd.read_csv('./dataset_results/patchtst_loss_functions_results_unscaled_minmax_0_5_relu.csv')[['Pred_len', 'Loss_function', 'RMSE', 'MAE']]

# Set 'Pred_len' and 'Loss_function' as index for each dataframe
standard_informer.set_index(['Pred_len', 'Loss_function'], inplace=True)
standard_patchtst.set_index(['Pred_len', 'Loss_function'], inplace=True)

minmax_0_1_relu_informer.set_index(['Pred_len', 'Loss_function'], inplace=True)
minmax_0_1_relu_patchtst.set_index(['Pred_len', 'Loss_function'], inplace=True)

minmax_0_5_relu_informer.set_index(['Pred_len', 'Loss_function'], inplace=True)
minmax_0_5_relu_patchtst.set_index(['Pred_len', 'Loss_function'], inplace=True)

# Concatenate all results
informer_df = pd.concat([
    standard_informer, 
    minmax_0_1_relu_informer, 
    minmax_0_5_relu_informer
], axis=1)

patchtst_df = pd.concat([
    standard_patchtst, 
    minmax_0_1_relu_patchtst, 
    minmax_0_5_relu_patchtst
], axis=1)

# Define the scalers and metrics
scalers = ['Standard', 'MinMax (0, 1)', 'MinMax (0, 5)']
metrics = ['RMSE', 'MAE']

# Create the MultiIndex for columns
multi_index_columns = pd.MultiIndex.from_product([scalers, metrics], names=['Scaler', 'Metrics'])

# Assign the MultiIndex to dataframes
informer_df.columns = multi_index_columns
patchtst_df.columns = multi_index_columns

# Groupby iterations
informer_df = informer_df.groupby(['Pred_len', 'Loss_function']).mean()
patchtst_df = patchtst_df.groupby(['Pred_len', 'Loss_function']).mean()

# Round for better readability
informer_df = informer_df.round(2)
patchtst_df = patchtst_df.round(2)

In [32]:
informer_df

Scaler                 Standard          MinMax (0, 1)          MinMax (0, 5)  \
Metrics                    RMSE      MAE          RMSE      MAE          RMSE
Pred_len Loss_function
24       MAE            4407.64  2752.20       5588.75  3367.64       4507.57
         MSE            4455.03  2946.11       4526.17  2885.32       4396.65
         RMSE           4439.07  2936.45       4455.19  2889.54       4417.32
96       MAE            6279.89  3962.91       6294.77  3947.22       6105.46
         MSE            6072.11  4183.22       6195.48  4106.60       6026.90
         RMSE           5979.53  4107.47       6125.46  4070.44       6018.72
168      MAE            6335.66  4107.52       6364.41  4086.26       6225.14
         MSE            6272.82  4301.43       6276.28  4214.17       6141.99
         RMSE           6285.67  4218.70       6275.91  4201.88       6372.76

Scaler
Metrics                     MAE
Pred_len Loss_function
24       MAE            2755.82
         MSE            2850.58
         RMSE           2853.74
96       MAE            3950.84
         MSE            4025.70
         RMSE           4021.30
168      MAE            4068.94
         MSE            4109.55
         RMSE           4206.55

In [33]:
patchtst_df

Scaler                 Standard          MinMax (0, 1)          MinMax (0, 5)  \
Metrics                    RMSE      MAE          RMSE      MAE          RMSE
Pred_len Loss_function
24       MAE            4114.63  2443.75       4096.46  2414.73       4099.44
         MSE            4184.65  2610.19       4140.12  2566.63       4137.13
         RMSE           4162.42  2633.37       4143.49  2564.95       4146.42
96       MAE            5747.14  3579.87       5676.51  3500.01       5654.47
         MSE            5641.55  3690.14       5648.63  3629.84       5693.63
         RMSE           5669.84  3715.34       5649.15  3637.77       5661.98
168      MAE            5871.54  3742.98       5932.94  3727.11       5940.01
         MSE            5893.68  3902.36       5878.97  3826.17       5874.90
         RMSE           5892.94  3902.30       5863.00  3833.77       5888.09

Scaler
Metrics                     MAE
Pred_len Loss_function
24       MAE            2422.23
         MSE            2570.86
         RMSE           2567.93
96       MAE            3479.29
         MSE            3672.36
         RMSE           3648.41
168      MAE            3719.48
         MSE            3831.98
         RMSE           3826.71